import{a as f,S as w,i as n}from"./assets/vendor-YT4DRQk6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const u=t=>`<li class="gallery-card">
        <a href="${t.largeImageURL}" class="gallery-link">
            <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
            </a>
             <div class="gallery-info">
              <p><strong>Likes:</strong> ${t.likes}</p>
              <p><strong>Views:</strong> ${t.views}</p>
              <p><strong>Comments:</strong> ${t.comments}</p>
              <p><strong>Downloads:</strong> ${t.downloads}</p>
            </div>
          </li>`,h=(t,e)=>{const o={params:{key:"46917062-2aeb1fc3b978e5a238a42f10e",q:t,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return f.get("https://pixabay.com/api/",o)},y=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),l=document.querySelector(".js-loadmore-btn");let d=1,i="";const m=new w(".gallery-link",{captionsData:"alt",captionDelay:50}),L=async t=>{try{if(t.preventDefault(),i=t.currentTarget.elements.user_query.value.trim(),i===""){n.show({message:"the field must be filled!"});return}d=1,l.classList.add("is-hidden"),loader.style.display="flex",c.innerHTML="";const{data:e}=await h(i,d);if(e.total===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!"}),y.reset();return}const o=e.hits.map(a=>u(a)).join("");c.innerHTML=o,m.refresh(),e.totalHits>15?l.classList.remove("is-hidden"):l.classList.add("is-hidden"),p()}catch(e){console.log(e),n.show({message:"Something went wrong. Please try again later."})}finally{loader.style.display="none"}},b=async t=>{try{d++;const{data:e}=await h(i,d),o=e.hits.map(a=>u(a)).join("");c.insertAdjacentHTML("beforeend",o),p(),m.refresh(),(e.hits.length<1||e.total===c.children.length)&&(l.classList.add("is-hidden"),n.show({message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.log(e),n.show({message:"Something went wrong. Please try again later."})}};y.addEventListener("submit",L);l.addEventListener("click",b);function p(){const t=document.querySelector(".gallery-card");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
