import{a as w,S as L,i as l}from"./assets/vendor-YT4DRQk6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&a(g)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const h=t=>`<li class="gallery-card">
        <a href="${t.largeImageURL}" class="gallery-link">
            <img class="gallery-img" src="${t.webformatURL}" alt="${t.tags}" />
            </a>
             <div class="gallery-info">
              <p><strong>Likes:</strong> ${t.likes}</p>
              <p><strong>Views:</strong> ${t.views}</p>
              <p><strong>Comments:</strong> ${t.comments}</p>
              <p><strong>Downloads:</strong> ${t.downloads}</p>
            </div>
          </li>`,y=(t,e)=>{const o={params:{key:"46917062-2aeb1fc3b978e5a238a42f10e",q:t,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}};return w.get("https://pixabay.com/api/",o)},m=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),n=document.querySelector(".js-loadmore-btn");let d=1,i="";const p=new L(".gallery-link",{captionsData:"alt",captionDelay:50}),b=async t=>{try{if(t.preventDefault(),i=t.currentTarget.elements.user_query.value.trim(),i===""){l.show({message:"the field must be filled!"});return}d=1,n.classList.add("is-hidden"),loader.style.display="flex";const{data:e}=await y(i,d);if(e.total===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!"}),c.innerHTML="",m.reset();return}e.total>1&&(n.classList.remove("is-hidden"),n.removeEventListener("click",u),n.addEventListener("click",u));const o=e.hits.map(a=>h(a)).join("");c.innerHTML=o,f(),p.refresh()}catch(e){console.log(e),l.show({message:"Something went wrong. Please try again later."})}finally{loader.style.display="none"}};m.addEventListener("submit",b);const u=async t=>{try{d++;const{data:e}=await y(i,d),o=e.hits.map(a=>h(a)).join("");c.insertAdjacentHTML("beforeend",o),f(),p.refresh(),(e.hits.length<1||e.total===c.children.length)&&(n.classList.add("is-hidden"),l.show({message:"We're sorry, but you've reached the end of search results."}))}catch(e){console.log(e),l.show({message:"Something went wrong. Please try again later."})}};n.addEventListener("click",u);function f(){const t=document.querySelector(".gallery-card");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
